name: eda-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # or 3.11
  - pandas
  - numpy
  - seaborn
  - scikit-learn
  - lightgbm
  - shap
  - optuna
  - matplotlib
  - polars
  - openpyxl
  - scipy
  - pytest
  - pytest-cov
  - pytest-mock
  - pyyaml
  - tabulate